import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { create } from "zustand";
import { hehe } from "~/utils/api";
import { useRouter } from "next/router";
import { persist, createJSONStorage } from "zustand/middleware";
import { anotherRouter } from "~/server/api/routers/anotherrouter";
import { Card } from "~/components/Card";
import { useEffect, useState } from "react";

export const useUserStore = create(
  persist(
    (set:any) => ({
      user: "abhi toh yeh hai",
      setUser: (e: any) => set(() => ({ user: e })),
    }),
    {
      name: "username-storage", // name of the item in the storage (must be unique)
      storage: createJSONStorage(() => localStorage), // (optional) by default, 'localStorage' is used
    }
  )
);



const Home: NextPage = () => {

    const todo =hehe.another.getAllOfOne.useQuery("awesamarth")
    const delMutation = hehe.another.deleteThat.useMutation()
    const [tasks, setTasks] = useState(todo.data);
    console.log(tasks)

    const handleDelMutation = async(id:number)=>{

        try {
            delMutation.mutate(id)
            console.log("done that")
            setTasks((prevTasks) => prevTasks?.filter((task) => task.id !== id));

            
        } catch (error) {
            console.error(error)
        }
    }

    useEffect(() => {
        if (todo.data) {
          setTasks(todo.data);
        }
      }, [todo.data]);


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="mt-4  w-[90%] border-2 grid grid-cols-3 gap-7">
        {tasks?.map((e) => (
    <Card data={e.task} key={e.id} deleter={()=>{handleDelMutation(e.id)}}  />
  ))}

        </div>
      </main>
    </>
  );
};

export default Home;
